# Generated by Django 2.2.6 on 2019-11-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0006_auto_20191105_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='index',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
    ]
