# Generated by Django 2.2.6 on 2019-11-05 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('project', '0001_initial'),
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbacklogitem',
            name='sprint_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sprints.SprintBacklog'),
        ),
        migrations.AddField(
            model_name='productbacklog',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
