# Generated by Django 2.2.7 on 2019-11-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191107_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbacklogitem',
            name='status',
            field=models.CharField(choices=[('TD', 'To Do'), ('IP', 'In Progress'), ('DO', 'Done'), ('UF', 'Unfinished')], default='TD', max_length=20),
        ),
    ]
