# Generated by Django 2.2.6 on 2019-11-02 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effort', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('pb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ProductBacklog')),
                ('sprint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.SprintBacklog')),
            ],
        ),
    ]
