# Generated by Django 2.2.7 on 2019-12-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191207_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbacklogitem',
            name='priority',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
