# Generated by Django 2.2.6 on 2019-11-05 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_pbi_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='pb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductBacklog'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sprints.SprintBacklog'),
        ),
    ]
