# Generated by Django 2.2.6 on 2019-11-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191105_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbacklogitem',
            old_name='name',
            new_name='title',
        ),
    ]
