# Generated by Django 2.2.6 on 2019-11-02 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='pb_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sprint_id',
        ),
    ]
