# Generated by Django 2.2.6 on 2019-11-02 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20191102_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='HI', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productbacklogitem',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productbacklogitem',
            name='sprint_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.SprintBacklog'),
        ),
    ]
