# Generated by Django 2.2.6 on 2019-11-02 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20191102_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pbi_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.ProductBacklogItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='sprint_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.SprintBacklog'),
            preserve_default=False,
        ),
    ]
